title: MOSAIC
description: WebRTC-based real-time robot control and monitoring system
theme: just-the-docs

url: https://acsl-mosaic.github.io

aux_links:
  GitHub: https://github.com/AutoCompSysLab/MOSAIC

defaults:
  - scope:
      path: ""
    values:
      layout: default
